name: fastlyzer
base: core18
version: '0.2.0'
summary: A log reader and analyzer
description: |
  Originally designed to analyze Fastly logs but can be used for any log file containing one JSON entry per line.

grade: devel # change this to stable once we reach 1.0
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  fastlyzer:
    plugin: rust
    source: .
    build-packages:
      - make
      - libjemalloc-dev

apps:
  fastlyzer:
    command: bin/fastlyzer
